Remove erroneous semicolon usage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -86,12 +86,12 @@ commands:
       - run:
           name: Determine deploy strategy
           command: |
-            # NOTE: The || true is included to suppress exit codes which would
-            #       cause the step to exit early due to use of pipefail
+            # NOTE: The || true is a no-op included to suppress exit codes which
+            #       would cause the step to exit early due to use of pipefail
             APP_GUID=$(cf app <<parameters.appname>> || true)
             if [ "$APP_GUID" == "FAILED" ]; then
               echo "export DEPLOY_STRATEGY=initial" >> $BASH_ENV
-            else;
+            else
               echo "export DEPLOY_STRATEGY=rolling" >> $BASH_ENV
             fi
 
